### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by AgustinMC09** [Sintya4/Advance-Moderation-v6#1]
C:\node_modules\discord.js\src\client\Client.js:489
      throw new DiscordjsTypeError(ErrorCodes.ClientMissingIntents);
      ^

TypeError [ClientMissingIntents]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\node_modules\discord.js\src\client\Client.js:489:13)
    at new Client (C:\node_modules\discord.js\src\client\Client.js:78:10)
    at Object.<anonymous> (C:\index.js:2:16)     
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)        
    at node:internal/main/run_main_module:17:47 {
  code: 'ClientMissingIntents'
}

**Comment by RappyTV** [comment]
did you update the discord.js version?
